import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
// @ts-ignore - server build is generated by Vite
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext: (context) => context.env,
});
