import { createRequestHandler } from "@remix-run/cloudflare";
// @ts-ignore – build output is generated by Vite
import * as build from "../build/server";
import type { AppEnv } from "./lib/env.server";
import { handleProcessingQueueBatch } from "./lib/queue/processing-worker.server";
import type { ProcessingQueueMessage } from "./lib/queue/messages.server";
import { refreshAllPodcastFeeds, RSS_REFRESH_BATCH_SIZE } from "./lib/services/rss-refresh.server";

// Remix request handler for SSR
const requestHandler = createRequestHandler(build as any);

export default {
  /**
   * HTTP requests → Remix SSR
   * Static assets (JS/CSS/images) are served via wrangler [assets] automatically
   * before this handler is called.
   */
  async fetch(request: Request, env: AppEnv, ctx: ExecutionContext): Promise<Response> {
    return requestHandler(request, env as any);
  },

  /**
   * Cron trigger: refresh all RSS feeds every 30 minutes.
   */
  async scheduled(_controller: ScheduledController, env: AppEnv, _ctx: ExecutionContext): Promise<void> {
    const result = await refreshAllPodcastFeeds(env.DB, { batchSize: RSS_REFRESH_BATCH_SIZE });
    console.log("RSS refresh cron completed", result);
  },

  /**
   * Queue consumer: process transcription and analysis jobs.
   */
  async queue(batch: MessageBatch<ProcessingQueueMessage>, env: AppEnv): Promise<void> {
    await handleProcessingQueueBatch(env, batch);
  },
};
