CREATE TABLE knowledge_search_docs (
 key TEXT NOT NULL UNIQUE,kind TEXT NOT NULL,object_id TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 0,
 source_type TEXT NOT NULL DEFAULT '',source_id TEXT NOT NULL DEFAULT '',
 title TEXT NOT NULL,body TEXT NOT NULL,tokens TEXT NOT NULL DEFAULT '',position REAL NOT NULL DEFAULT 0,segment_id TEXT NOT NULL DEFAULT '',
 snapshot_id TEXT NOT NULL DEFAULT '',visibility TEXT NOT NULL DEFAULT 'current',
 created_at TEXT NOT NULL,updated_at TEXT NOT NULL
);
CREATE INDEX idx_knowledge_search_scope ON knowledge_search_docs(kind,source_type,source_id,visibility,created_at);
CREATE VIRTUAL TABLE knowledge_search_fts USING fts5(tokens,content='knowledge_search_docs',content_rowid='rowid',tokenize='unicode61');
CREATE TRIGGER knowledge_search_insert AFTER INSERT ON knowledge_search_docs BEGIN
 INSERT INTO knowledge_search_fts(rowid,tokens)VALUES(new.rowid,new.tokens);END;
CREATE TRIGGER knowledge_search_delete AFTER DELETE ON knowledge_search_docs BEGIN
 INSERT INTO knowledge_search_fts(knowledge_search_fts,rowid,tokens)VALUES('delete',old.rowid,old.tokens);END;
CREATE TRIGGER knowledge_search_update AFTER UPDATE ON knowledge_search_docs BEGIN
 INSERT INTO knowledge_search_fts(knowledge_search_fts,rowid,tokens)VALUES('delete',old.rowid,old.tokens);
 INSERT INTO knowledge_search_fts(rowid,tokens)VALUES(new.rowid,new.tokens);END;
INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'note:'||n.id,n.kind,n.id,n.revision,n.source_type,n.source_id,CASE WHEN n.kind='source_note' THEN '来源笔记' ELSE '我的理解' END,n.content,cwp_search_tokens(n.content),COALESCE(json_extract(n.anchor_json,'$.position'),0),COALESCE(json_extract(n.anchor_json,'$.segment_ids[0]'),''),COALESCE(json_extract(n.anchor_json,'$.snapshot_id'),''),'current',n.created_at,n.updated_at FROM owner_notes n;
INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'keypoint:'||k.id,'keypoint',k.id,k.card_version,k.source_type,k.source_id,k.source_title,k.content||char(10)||k.description,cwp_search_tokens(k.source_title||' '||k.content||' '||k.description),CASE WHEN k.source_type='document' THEN CAST(substr(json_extract(k.citations_json,'$[0]'),length(k.source_id)+3) AS INTEGER) ELSE k.time_start END,COALESCE(json_extract(k.citations_json,'$[0]'),''),'','current',k.created_at,k.created_at FROM keypoint_index k WHERE k.stale_at IS NULL AND k.evidence_status!='stale' AND k.production_status!='dismissed';
INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'document:'||d.id||':'||json_extract(seg.value,'$.ID'),'document',d.id,d.version,'document',d.id,d.title,json_extract(seg.value,'$.Text'),cwp_search_tokens(d.title||' '||json_extract(seg.value,'$.Text')),json_extract(seg.value,'$.Position'),json_extract(seg.value,'$.ID'),'','current',d.created_at,d.updated_at FROM documents d,json_each(cwp_document_segments(d.id,d.content)) seg;
INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'article:'||r.article_id||':'||r.revision||':'||block.key,'article',r.article_id,r.revision,'','',r.title,json_extract(block.value,'$.text'),cwp_search_tokens(r.title||' '||json_extract(block.value,'$.text')),CAST(block.key AS INTEGER),'','',CASE WHEN r.evidence_status!='valid' THEN 'invalid' WHEN a.passed_revision=r.revision THEN 'current' WHEN a.working_revision=r.revision THEN 'draft' ELSE 'history' END,r.created_at,r.created_at FROM knowledge_article_revisions r JOIN knowledge_articles a ON a.id=r.article_id,json_each(r.blocks_json) block WHERE 1=1;
CREATE TRIGGER knowledge_notes_insert AFTER INSERT ON owner_notes BEGIN
DELETE FROM knowledge_search_docs WHERE key='note:'||new.id;
 INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'note:'||n.id,n.kind,n.id,n.revision,n.source_type,n.source_id,CASE WHEN n.kind='source_note' THEN '来源笔记' ELSE '我的理解' END,n.content,cwp_search_tokens(n.content),COALESCE(json_extract(n.anchor_json,'$.position'),0),COALESCE(json_extract(n.anchor_json,'$.segment_ids[0]'),''),COALESCE(json_extract(n.anchor_json,'$.snapshot_id'),''),'current',n.created_at,n.updated_at FROM owner_notes n WHERE n.id=new.id;
END;
CREATE TRIGGER knowledge_notes_update AFTER UPDATE ON owner_notes BEGIN
DELETE FROM knowledge_search_docs WHERE key='note:'||new.id;
 INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'note:'||n.id,n.kind,n.id,n.revision,n.source_type,n.source_id,CASE WHEN n.kind='source_note' THEN '来源笔记' ELSE '我的理解' END,n.content,cwp_search_tokens(n.content),COALESCE(json_extract(n.anchor_json,'$.position'),0),COALESCE(json_extract(n.anchor_json,'$.segment_ids[0]'),''),COALESCE(json_extract(n.anchor_json,'$.snapshot_id'),''),'current',n.created_at,n.updated_at FROM owner_notes n WHERE n.id=new.id;
END;
CREATE TRIGGER knowledge_notes_delete AFTER DELETE ON owner_notes BEGIN DELETE FROM knowledge_search_docs WHERE key='note:'||old.id;END;
CREATE TRIGGER knowledge_keys_insert AFTER INSERT ON keypoint_index BEGIN
DELETE FROM knowledge_search_docs WHERE key='keypoint:'||new.id;
 INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'keypoint:'||k.id,'keypoint',k.id,k.card_version,k.source_type,k.source_id,k.source_title,k.content||char(10)||k.description,cwp_search_tokens(k.source_title||' '||k.content||' '||k.description),CASE WHEN k.source_type='document' THEN CAST(substr(json_extract(k.citations_json,'$[0]'),length(k.source_id)+3) AS INTEGER) ELSE k.time_start END,COALESCE(json_extract(k.citations_json,'$[0]'),''),'','current',k.created_at,k.created_at FROM keypoint_index k WHERE k.stale_at IS NULL AND k.evidence_status!='stale' AND k.production_status!='dismissed' AND k.id=new.id;
END;
CREATE TRIGGER knowledge_keys_update AFTER UPDATE ON keypoint_index BEGIN
DELETE FROM knowledge_search_docs WHERE key='keypoint:'||new.id;
 INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'keypoint:'||k.id,'keypoint',k.id,k.card_version,k.source_type,k.source_id,k.source_title,k.content||char(10)||k.description,cwp_search_tokens(k.source_title||' '||k.content||' '||k.description),CASE WHEN k.source_type='document' THEN CAST(substr(json_extract(k.citations_json,'$[0]'),length(k.source_id)+3) AS INTEGER) ELSE k.time_start END,COALESCE(json_extract(k.citations_json,'$[0]'),''),'','current',k.created_at,k.created_at FROM keypoint_index k WHERE k.stale_at IS NULL AND k.evidence_status!='stale' AND k.production_status!='dismissed' AND k.id=new.id;
END;
CREATE TRIGGER knowledge_keys_delete AFTER DELETE ON keypoint_index BEGIN DELETE FROM knowledge_search_docs WHERE key='keypoint:'||old.id;END;
CREATE TRIGGER knowledge_docs_insert AFTER INSERT ON documents BEGIN
DELETE FROM knowledge_search_docs WHERE kind='document' AND object_id=new.id;
 INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'document:'||d.id||':'||json_extract(seg.value,'$.ID'),'document',d.id,d.version,'document',d.id,d.title,json_extract(seg.value,'$.Text'),cwp_search_tokens(d.title||' '||json_extract(seg.value,'$.Text')),json_extract(seg.value,'$.Position'),json_extract(seg.value,'$.ID'),'','current',d.created_at,d.updated_at FROM documents d,json_each(cwp_document_segments(d.id,d.content)) seg WHERE d.id=new.id;
END;
CREATE TRIGGER knowledge_docs_update AFTER UPDATE ON documents BEGIN
DELETE FROM knowledge_search_docs WHERE kind='document' AND object_id=new.id;
 INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'document:'||d.id||':'||json_extract(seg.value,'$.ID'),'document',d.id,d.version,'document',d.id,d.title,json_extract(seg.value,'$.Text'),cwp_search_tokens(d.title||' '||json_extract(seg.value,'$.Text')),json_extract(seg.value,'$.Position'),json_extract(seg.value,'$.ID'),'','current',d.created_at,d.updated_at FROM documents d,json_each(cwp_document_segments(d.id,d.content)) seg WHERE d.id=new.id;
END;
CREATE TRIGGER knowledge_docs_delete AFTER DELETE ON documents BEGIN DELETE FROM knowledge_search_docs WHERE kind='document' AND object_id=old.id;END;
INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'original:episode:'||s.id||':'||COALESCE(json_extract(seg.value,'$.id'),seg.key),'original',s.id,a.version,'episode',s.id,s.title,json_extract(seg.value,'$.text'),cwp_search_tokens(s.title||' '||json_extract(seg.value,'$.text')),COALESCE(json_extract(seg.value,'$.start'),0),COALESCE(json_extract(seg.value,'$.id'),''),'','current',a.created_at,a.created_at FROM episodes s JOIN artifact_versions a ON a.source_type='episode' AND a.source_id=s.id AND a.kind='transcript' AND a.version=s.current_transcript_version,json_each(CASE WHEN json_valid(a.payload) THEN a.payload ELSE '{"segments":[]}' END,'$.segments') seg;
CREATE TRIGGER knowledge_original_episode_update AFTER UPDATE OF current_transcript_version,title ON episodes BEGIN DELETE FROM knowledge_search_docs WHERE kind='original' AND source_type='episode' AND source_id=new.id; INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'original:episode:'||s.id||':'||COALESCE(json_extract(seg.value,'$.id'),seg.key),'original',s.id,a.version,'episode',s.id,s.title,json_extract(seg.value,'$.text'),cwp_search_tokens(s.title||' '||json_extract(seg.value,'$.text')),COALESCE(json_extract(seg.value,'$.start'),0),COALESCE(json_extract(seg.value,'$.id'),''),'','current',a.created_at,a.created_at FROM episodes s JOIN artifact_versions a ON a.source_type='episode' AND a.source_id=s.id AND a.kind='transcript' AND a.version=s.current_transcript_version,json_each(CASE WHEN json_valid(a.payload) THEN a.payload ELSE '{"segments":[]}' END,'$.segments') seg WHERE s.id=new.id;END;
CREATE TRIGGER knowledge_original_episode_delete AFTER DELETE ON episodes BEGIN DELETE FROM knowledge_search_docs WHERE source_type='episode' AND source_id=old.id;END;
INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'original:upload:'||s.id||':'||COALESCE(json_extract(seg.value,'$.id'),seg.key),'original',s.id,a.version,'upload',s.id,s.original_filename,json_extract(seg.value,'$.text'),cwp_search_tokens(s.original_filename||' '||json_extract(seg.value,'$.text')),COALESCE(json_extract(seg.value,'$.start'),0),COALESCE(json_extract(seg.value,'$.id'),''),'','current',a.created_at,a.created_at FROM uploads s JOIN artifact_versions a ON a.source_type='upload' AND a.source_id=s.id AND a.kind='transcript' AND a.version=s.current_transcript_version,json_each(CASE WHEN json_valid(a.payload) THEN a.payload ELSE '{"segments":[]}' END,'$.segments') seg;
CREATE TRIGGER knowledge_original_upload_update AFTER UPDATE OF current_transcript_version,original_filename ON uploads BEGIN DELETE FROM knowledge_search_docs WHERE kind='original' AND source_type='upload' AND source_id=new.id; INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'original:upload:'||s.id||':'||COALESCE(json_extract(seg.value,'$.id'),seg.key),'original',s.id,a.version,'upload',s.id,s.original_filename,json_extract(seg.value,'$.text'),cwp_search_tokens(s.original_filename||' '||json_extract(seg.value,'$.text')),COALESCE(json_extract(seg.value,'$.start'),0),COALESCE(json_extract(seg.value,'$.id'),''),'','current',a.created_at,a.created_at FROM uploads s JOIN artifact_versions a ON a.source_type='upload' AND a.source_id=s.id AND a.kind='transcript' AND a.version=s.current_transcript_version,json_each(CASE WHEN json_valid(a.payload) THEN a.payload ELSE '{"segments":[]}' END,'$.segments') seg WHERE s.id=new.id;END;
CREATE TRIGGER knowledge_original_upload_delete AFTER DELETE ON uploads BEGIN DELETE FROM knowledge_search_docs WHERE source_type='upload' AND source_id=old.id;END;
CREATE TRIGGER knowledge_revision_insert AFTER INSERT ON knowledge_article_revisions BEGIN DELETE FROM knowledge_search_docs WHERE kind='article' AND object_id=new.article_id; INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'article:'||r.article_id||':'||r.revision||':'||block.key,'article',r.article_id,r.revision,'','',r.title,json_extract(block.value,'$.text'),cwp_search_tokens(r.title||' '||json_extract(block.value,'$.text')),CAST(block.key AS INTEGER),'','',CASE WHEN r.evidence_status!='valid' THEN 'invalid' WHEN a.passed_revision=r.revision THEN 'current' WHEN a.working_revision=r.revision THEN 'draft' ELSE 'history' END,r.created_at,r.created_at FROM knowledge_article_revisions r JOIN knowledge_articles a ON a.id=r.article_id,json_each(r.blocks_json) block WHERE 1=1 AND a.id=new.article_id;END;
CREATE TRIGGER knowledge_revision_state AFTER UPDATE ON knowledge_article_revisions BEGIN DELETE FROM knowledge_search_docs WHERE kind='article' AND object_id=new.article_id; INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'article:'||r.article_id||':'||r.revision||':'||block.key,'article',r.article_id,r.revision,'','',r.title,json_extract(block.value,'$.text'),cwp_search_tokens(r.title||' '||json_extract(block.value,'$.text')),CAST(block.key AS INTEGER),'','',CASE WHEN r.evidence_status!='valid' THEN 'invalid' WHEN a.passed_revision=r.revision THEN 'current' WHEN a.working_revision=r.revision THEN 'draft' ELSE 'history' END,r.created_at,r.created_at FROM knowledge_article_revisions r JOIN knowledge_articles a ON a.id=r.article_id,json_each(r.blocks_json) block WHERE 1=1 AND a.id=new.article_id;END;
CREATE TRIGGER knowledge_article_selection AFTER UPDATE ON knowledge_articles BEGIN DELETE FROM knowledge_search_docs WHERE kind='article' AND object_id=new.id; INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'article:'||r.article_id||':'||r.revision||':'||block.key,'article',r.article_id,r.revision,'','',r.title,json_extract(block.value,'$.text'),cwp_search_tokens(r.title||' '||json_extract(block.value,'$.text')),CAST(block.key AS INTEGER),'','',CASE WHEN r.evidence_status!='valid' THEN 'invalid' WHEN a.passed_revision=r.revision THEN 'current' WHEN a.working_revision=r.revision THEN 'draft' ELSE 'history' END,r.created_at,r.created_at FROM knowledge_article_revisions r JOIN knowledge_articles a ON a.id=r.article_id,json_each(r.blocks_json) block WHERE 1=1 AND a.id=new.id;END;
CREATE TRIGGER knowledge_article_delete AFTER DELETE ON knowledge_articles BEGIN DELETE FROM knowledge_search_docs WHERE kind='article' AND object_id=old.id;END;

-- Keep invalidation independent from processing status. Frozen bodies remain readable.
CREATE TRIGGER knowledge_episode_evidence_changed AFTER UPDATE OF current_transcript_version,archived_at ON episodes WHEN new.current_transcript_version IS NOT old.current_transcript_version OR new.archived_at IS NOT old.archived_at BEGIN
 UPDATE knowledge_article_revisions SET evidence_status='outdated' WHERE (article_id,revision) IN(SELECT article_id,revision FROM knowledge_article_material_refs WHERE source_type='episode' AND source_id=new.id);
END;
CREATE TRIGGER knowledge_upload_evidence_changed AFTER UPDATE OF current_transcript_version,archived_at ON uploads WHEN new.current_transcript_version IS NOT old.current_transcript_version OR new.archived_at IS NOT old.archived_at BEGIN
 UPDATE knowledge_article_revisions SET evidence_status='outdated' WHERE (article_id,revision) IN(SELECT article_id,revision FROM knowledge_article_material_refs WHERE source_type='upload' AND source_id=new.id);
END;
CREATE TRIGGER knowledge_document_archived AFTER UPDATE OF archived_at ON documents WHEN new.archived_at IS NOT old.archived_at BEGIN
 UPDATE knowledge_article_revisions SET evidence_status='outdated' WHERE (article_id,revision) IN(SELECT article_id,revision FROM knowledge_article_material_refs WHERE source_type='document' AND source_id=new.id);
END;

-- Legacy segment index remains usable only when no current artifact identity exists.
INSERT INTO knowledge_search_docs(key,kind,object_id,revision,source_type,source_id,title,body,tokens,position,segment_id,snapshot_id,visibility,created_at,updated_at) SELECT 'original:'||x.source_type||':'||x.source_id||':'||x.segment_id,'original',x.source_id,0,x.source_type,x.source_id,x.title,x.body,cwp_search_tokens(x.title||' '||x.body),x.start,x.segment_id,'','current',datetime('now'),datetime('now') FROM search_index x WHERE x.segment_id!='' AND NOT EXISTS(SELECT 1 FROM knowledge_search_docs d WHERE d.key='original:'||x.source_type||':'||x.source_id||':'||x.segment_id) AND NOT EXISTS(SELECT 1 FROM artifact_versions a LEFT JOIN episodes e ON e.id=a.source_id AND a.source_type='episode' LEFT JOIN uploads u ON u.id=a.source_id AND a.source_type='upload' WHERE a.kind='transcript' AND a.source_type=x.source_type AND a.source_id=x.source_id AND a.version=COALESCE(e.current_transcript_version,u.current_transcript_version));

CREATE TRIGGER knowledge_original_episode_error AFTER UPDATE OF current_transcript_version ON episodes BEGIN
 DELETE FROM knowledge_search_docs WHERE kind='index_error' AND source_type='episode' AND source_id=new.id;
 INSERT INTO knowledge_search_docs(key,kind,object_id,source_type,source_id,title,body,created_at,updated_at) SELECT 'index-error:episode:'||new.id,'index_error',new.id,'episode',new.id,'索引不完整','转录JSON损坏',datetime('now'),datetime('now') FROM artifact_versions a WHERE a.source_type='episode' AND a.source_id=new.id AND a.kind='transcript' AND a.version=new.current_transcript_version AND NOT json_valid(a.payload);
END;

CREATE TRIGGER knowledge_original_upload_error AFTER UPDATE OF current_transcript_version ON uploads BEGIN
 DELETE FROM knowledge_search_docs WHERE kind='index_error' AND source_type='upload' AND source_id=new.id;
 INSERT INTO knowledge_search_docs(key,kind,object_id,source_type,source_id,title,body,created_at,updated_at) SELECT 'index-error:upload:'||new.id,'index_error',new.id,'upload',new.id,'索引不完整','转录JSON损坏',datetime('now'),datetime('now') FROM artifact_versions a WHERE a.source_type='upload' AND a.source_id=new.id AND a.kind='transcript' AND a.version=new.current_transcript_version AND NOT json_valid(a.payload);
END;

INSERT INTO knowledge_search_docs(key,kind,object_id,source_type,source_id,title,body,created_at,updated_at) SELECT 'index-error:'||a.source_type||':'||a.source_id,'index_error',a.source_id,a.source_type,a.source_id,'索引不完整','转录JSON损坏',datetime('now'),datetime('now') FROM artifact_versions a JOIN (SELECT 'episode' AS source_type,id,current_transcript_version AS version FROM episodes UNION ALL SELECT 'upload',id,current_transcript_version FROM uploads) current ON current.source_type=a.source_type AND current.id=a.source_id AND current.version=a.version WHERE a.kind='transcript' AND NOT json_valid(a.payload);
