-- Preserve existing run facts; new synthetic job directions have explicit lanes.
INSERT INTO run_controls(kind,target)VALUES('lane','study'),('lane','index'),('lane','export');
DROP TRIGGER run_control_admission;
DROP TRIGGER run_control_lane;
CREATE TRIGGER run_control_admission BEFORE INSERT ON processing_jobs
 WHEN EXISTS(SELECT 1 FROM run_controls WHERE paused=1 AND ((kind='lane' AND target=(CASE WHEN NEW.source_type IN('question_study','study_chat') AND NEW.job_type='question_study' THEN 'study' WHEN NEW.source_type='knowledge_index' AND NEW.job_type='knowledge_embedding' THEN 'index' WHEN NEW.source_type='learning_export' AND NEW.job_type='learning_export' THEN 'export' WHEN NEW.source_type='knowledge_article' THEN CASE WHEN json_extract(CASE WHEN json_valid(NEW.input_snapshot_json) THEN NEW.input_snapshot_json ELSE '{}' END,'$.request.update') IS NOT NULL OR json_extract(CASE WHEN json_valid(NEW.input_snapshot_json) THEN NEW.input_snapshot_json ELSE '{}' END,'$.stage')='update_propose' THEN 'updates' ELSE 'knowledge' END WHEN NEW.job_type='weekly_review' THEN 'review' WHEN NEW.source_type='voice_note' THEN 'voice' ELSE '' END)) OR (kind='direction' AND target=NEW.source_type||':'||NEW.source_id)))
 BEGIN SELECT RAISE(ABORT,'Owner运行控制已暂停'); END;
CREATE TRIGGER run_control_lane AFTER INSERT ON processing_jobs BEGIN
 UPDATE processing_jobs SET run_lane=CASE WHEN NEW.source_type IN('question_study','study_chat') AND NEW.job_type='question_study' THEN 'study' WHEN NEW.source_type='knowledge_index' AND NEW.job_type='knowledge_embedding' THEN 'index' WHEN NEW.source_type='learning_export' AND NEW.job_type='learning_export' THEN 'export' WHEN NEW.source_type='knowledge_article' THEN CASE WHEN json_extract(CASE WHEN json_valid(NEW.input_snapshot_json) THEN NEW.input_snapshot_json ELSE '{}' END,'$.request.update') IS NOT NULL OR json_extract(CASE WHEN json_valid(NEW.input_snapshot_json) THEN NEW.input_snapshot_json ELSE '{}' END,'$.stage')='update_propose' THEN 'updates' ELSE 'knowledge' END WHEN NEW.job_type='weekly_review' THEN 'review' WHEN NEW.source_type='voice_note' THEN 'voice' ELSE '' END WHERE id=NEW.id; END;
