CREATE TABLE understanding_heads(question_id TEXT PRIMARY KEY REFERENCES learning_questions(id) ON DELETE CASCADE,revision INTEGER NOT NULL DEFAULT 0,current_snapshot_id TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT(datetime('now')));
CREATE TABLE understanding_snapshots(id TEXT PRIMARY KEY,question_id TEXT NOT NULL REFERENCES learning_questions(id) ON DELETE CASCADE,version INTEGER NOT NULL,parent_id TEXT NOT NULL DEFAULT '',answer TEXT NOT NULL,uncertainty TEXT NOT NULL DEFAULT '',next_step TEXT NOT NULL DEFAULT '',model_data_policy TEXT NOT NULL DEFAULT 'local_only' CHECK(model_data_policy IN('local_only','external_allowed','approved_providers_only')),approved_providers_json TEXT NOT NULL DEFAULT '[]',request_key TEXT NOT NULL UNIQUE,payload_hash TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT(datetime('now')),UNIQUE(question_id,version));
CREATE TABLE understanding_references(snapshot_id TEXT NOT NULL REFERENCES understanding_snapshots(id) ON DELETE CASCADE,ordinal INTEGER NOT NULL,kind TEXT NOT NULL,object_id TEXT NOT NULL,version INTEGER NOT NULL,source_type TEXT NOT NULL DEFAULT '',source_id TEXT NOT NULL DEFAULT '',body TEXT NOT NULL DEFAULT '',purged INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(snapshot_id,ordinal));
CREATE INDEX understanding_reference_source ON understanding_references(source_type,source_id);
CREATE TRIGGER understanding_snapshot_index AFTER INSERT ON understanding_snapshots BEGIN INSERT INTO knowledge_search_docs(key,kind,object_id,revision,title,body,tokens,visibility,created_at,updated_at) SELECT 'understanding:'||new.id,'understanding',new.id,new.version,q.body||' · 我的理解',new.answer||char(10)||new.uncertainty||char(10)||new.next_step,cwp_search_tokens(q.body||' '||new.answer||' '||new.uncertainty||' '||new.next_step),'history',new.created_at,new.created_at FROM learning_questions q WHERE q.id=new.question_id; END;
CREATE TRIGGER understanding_current_index AFTER UPDATE OF current_snapshot_id ON understanding_heads BEGIN UPDATE knowledge_search_docs SET visibility=CASE WHEN object_id=new.current_snapshot_id THEN 'current' ELSE 'history' END WHERE kind='understanding' AND object_id IN(SELECT id FROM understanding_snapshots WHERE question_id=new.question_id); END;
CREATE TRIGGER understanding_snapshot_delete AFTER DELETE ON understanding_snapshots BEGIN DELETE FROM knowledge_search_docs WHERE kind='understanding' AND object_id=old.id; END;
CREATE TRIGGER understanding_episode_purge BEFORE DELETE ON episodes BEGIN UPDATE understanding_references SET body='',purged=1 WHERE (source_type='episode' AND source_id=old.id) OR (kind='article' AND EXISTS(SELECT 1 FROM knowledge_article_material_refs am WHERE am.article_id=understanding_references.object_id AND am.revision=understanding_references.version AND am.source_type='episode' AND am.source_id=old.id)); END;
CREATE TRIGGER understanding_upload_purge BEFORE DELETE ON uploads BEGIN UPDATE understanding_references SET body='',purged=1 WHERE (source_type='upload' AND source_id=old.id) OR (kind='article' AND EXISTS(SELECT 1 FROM knowledge_article_material_refs am WHERE am.article_id=understanding_references.object_id AND am.revision=understanding_references.version AND am.source_type='upload' AND am.source_id=old.id)); END;
CREATE TRIGGER understanding_document_purge BEFORE DELETE ON documents BEGIN UPDATE understanding_references SET body='',purged=1 WHERE (source_type='document' AND source_id=old.id) OR (kind='article' AND EXISTS(SELECT 1 FROM knowledge_article_material_refs am WHERE am.article_id=understanding_references.object_id AND am.revision=understanding_references.version AND am.source_type='document' AND am.source_id=old.id)); END;
CREATE TRIGGER understanding_evidence_purge AFTER UPDATE OF status ON source_snapshots WHEN new.status='purged' BEGIN UPDATE understanding_references SET body='',purged=1 WHERE source_type=new.source_type AND source_id=new.source_id; END;
CREATE TABLE understanding_choose_requests(request_key TEXT PRIMARY KEY,payload_hash TEXT NOT NULL,question_id TEXT NOT NULL REFERENCES learning_questions(id) ON DELETE CASCADE,snapshot_id TEXT NOT NULL REFERENCES understanding_snapshots(id) ON DELETE CASCADE);

CREATE TRIGGER understanding_current_change AFTER UPDATE OF current_snapshot_id ON understanding_heads WHEN new.current_snapshot_id!=old.current_snapshot_id BEGIN
 INSERT INTO knowledge_learning_changes(kind,material_id,source_type,source_id,material_version)VALUES('learning_question',new.question_id,'','',new.revision);
 INSERT INTO knowledge_learning_changes(kind,material_id,source_type,source_id,material_version) SELECT 'understanding',id,'','',version FROM understanding_snapshots WHERE id=new.current_snapshot_id;
END;
CREATE TRIGGER understanding_reference_purged AFTER UPDATE OF purged ON understanding_references WHEN new.purged=1 AND old.purged=0 BEGIN DELETE FROM knowledge_embedding_vectors WHERE doc_key='understanding:'||new.snapshot_id; UPDATE knowledge_embedding_state SET delete_epoch=delete_epoch+1,index_epoch=index_epoch+1 WHERE id=1; END;
CREATE TABLE knowledge_embedding_understandings(config_id TEXT NOT NULL REFERENCES knowledge_embedding_configs(id) ON DELETE CASCADE,snapshot_id TEXT NOT NULL REFERENCES understanding_snapshots(id) ON DELETE CASCADE,PRIMARY KEY(config_id,snapshot_id));
CREATE TABLE question_study_understandings(turn_id TEXT NOT NULL REFERENCES question_study_turns(id) ON DELETE CASCADE,snapshot_id TEXT NOT NULL REFERENCES understanding_snapshots(id) ON DELETE CASCADE,frozen_json TEXT NOT NULL,PRIMARY KEY(turn_id,snapshot_id));
CREATE TRIGGER understanding_reference_study_purge AFTER UPDATE OF purged ON understanding_references WHEN new.purged=1 AND old.purged=0 BEGIN UPDATE question_study_turns SET purged=1,state='blocked',owner_input='',frozen_json='{}',accepted_json='' WHERE id IN(SELECT turn_id FROM question_study_understandings WHERE snapshot_id=new.snapshot_id); UPDATE question_study_understandings SET frozen_json='{}' WHERE snapshot_id=new.snapshot_id; END;
-- Source cleanup may redact Reference projections inside derived frozen inputs,
-- while preserving the Owner answer and immutable version identity.
CREATE TRIGGER understanding_reference_article_redaction AFTER UPDATE OF purged ON understanding_references WHEN new.purged=1 AND old.purged=0 BEGIN
 UPDATE knowledge_article_revisions SET evidence_status='unavailable',input_json=json_set(input_json,'$.materials',json((SELECT json_group_array(json(CASE WHEN json_extract(m.value,'$.kind')='understanding' AND json_extract(m.value,'$.id')=new.snapshot_id THEN json_set(m.value,'$.understanding_references',json((SELECT json_group_array(json_object('kind',kind,'object_id',object_id,'version',version,'source_type',source_type,'source_id',source_id,'body',body,'purged',json(CASE WHEN purged=1 THEN 'true' ELSE 'false' END))) FROM understanding_references WHERE snapshot_id=new.snapshot_id))) ELSE m.value END)) FROM json_each(input_json,'$.materials') m))) WHERE EXISTS(SELECT 1 FROM json_each(input_json,'$.materials') m WHERE json_extract(m.value,'$.kind')='understanding' AND json_extract(m.value,'$.id')=new.snapshot_id);
 UPDATE knowledge_articles SET input_json=json_set(input_json,'$.materials',json((SELECT json_group_array(json(CASE WHEN json_extract(m.value,'$.kind')='understanding' AND json_extract(m.value,'$.id')=new.snapshot_id THEN json_set(m.value,'$.understanding_references',json((SELECT json_group_array(json_object('kind',kind,'object_id',object_id,'version',version,'source_type',source_type,'source_id',source_id,'body',body,'purged',json(CASE WHEN purged=1 THEN 'true' ELSE 'false' END))) FROM understanding_references WHERE snapshot_id=new.snapshot_id))) ELSE m.value END)) FROM json_each(input_json,'$.materials') m))) WHERE EXISTS(SELECT 1 FROM json_each(input_json,'$.materials') m WHERE json_extract(m.value,'$.kind')='understanding' AND json_extract(m.value,'$.id')=new.snapshot_id);
 UPDATE processing_jobs SET stop_requested=1,input_snapshot_json='{}',checkpoint_json='',result_json='{"purged":true}',last_error='理解参考来源已清理' WHERE job_type='knowledge_article' AND EXISTS(SELECT 1 FROM json_tree(CASE WHEN json_valid(input_snapshot_json) THEN input_snapshot_json ELSE '{}' END) j WHERE j.value=new.snapshot_id);
END;
CREATE TRIGGER understanding_article_reference_invalid AFTER UPDATE OF evidence_status ON knowledge_article_revisions WHEN new.evidence_status IN('unavailable','purged') BEGIN UPDATE understanding_references SET body='',purged=1 WHERE kind='article' AND object_id=new.article_id AND version=new.revision; END;
CREATE TRIGGER understanding_article_reference_delete BEFORE DELETE ON knowledge_articles BEGIN UPDATE understanding_references SET body='',purged=1 WHERE kind='article' AND object_id=old.id; END;

CREATE TRIGGER understanding_question_index_title AFTER UPDATE OF body ON learning_questions WHEN new.body!=old.body BEGIN UPDATE knowledge_search_docs SET title=new.body||' · 我的理解' WHERE kind='understanding' AND object_id IN(SELECT id FROM understanding_snapshots WHERE question_id=new.id); END;
